### PR TITLE
[Java]Fixed TieredIndexParams creation/destruction, calling cuvsTieredIndexParamsCreate 

### LINKED ISSUE #1138: [FIX][JAVA] Use C APIs for Tiered index params creation/free
Like we did for CAGRA and Bruteforce index Params (https://github.com/rapidsai/cuvs/pull/1109 and https://github.com/rapidsai/cuvs/pull/1110): the current code allocates data structures for Tiered index params CuVS objects manually, i.e. through a Java Arena. This is not supposed to happen: the CuVS C API provides an API for creating ad destroying these objects. 

At present, the code works as it is mimicking what the C API is doing, but if the C API changes (e.g. allocating more nested objects, or initializing the data structures with default values etc.) the Java API could break in a way that is difficult to track.

### PR DESCRIPTION
**Pull request by punAhuja**
Using `cuvsTieredIndexParamsCreate` and `cuvsTieredIndexParamsDestroy` now instead of allocating arena in Java.
  -Used CloseableHandle and CuvsParamsHelper as used in #1109 and #1110 for consistency
  
  This fixes #1138

### CODE REVIEW

**Comment by mythrocks** [comment]
Just a heads-up:  I'd like to get #1109 and #1110 in before we merge this change.  We will need to rebase this once those are merged.

Looks good to my eye, FWIW.  We'll just depend on #1109 for the definitions of `CloseableHandle`, etc.

**Comment by mythrocks** [comment]
@punAhuja:  #1109 has been merged.  This PR will need a rebase and its conflicts need resolution.  I'd offer to do this myself, but I don't have push-permissions on your branch.

It's a simple enough conflict to resolve:  `CuVSParamsHelper` has been merged in #1109.  One only need append `createTieredIndexParams()`'s definition at the end.

**Comment by punAhuja** [comment]
> @punAhuja: #1109 has been merged. This PR will need a rebase and its conflicts need resolution. I'd offer to do this myself, but I don't have push-permissions on your branch.
> 
> It's a simple enough conflict to resolve: `CuVSParamsHelper` has been merged in #1109. One only need append `createTieredIndexParams()`'s definition at the end.

Updated branch and resolved conflicts.

**Comment by mythrocks** [comment]
Sorry, this needs another rebase, already.

I would advise rebasing after #1111 is merged.

**Comment by punAhuja** [comment]
> Sorry, this needs another rebase, already.
> 
> I would advise rebasing after #1111 is merged.

Have updated the branch and resolved conflicts.

File: java/cuvs-java/src/main/java22/com/nvidia/cuvs/internal/CuVSParamsHelper.java [hunk 1]
```diff
@@ -151,4 +151,23 @@ public void close() {
       };
     }
   }
+
+  static CloseableHandle createTieredIndexParams() {
```
Comment (mythrocks) [inline java/cuvs-java/src/main/java22/com/nvidia/cuvs/internal/CuVSParamsHelper.java:155]: 👍

File: java/cuvs-java/src/main/java22/com/nvidia/cuvs/internal/TieredIndexImpl.java [hunk 2]
```diff
@@ -118,10 +120,11 @@ private IndexReference build() {
       long rows = dataset.size();
       long cols = dataset.columns();
 
-      MemorySegment indexParamsMemorySegment =
+      CloseableHandle indexParamsHandle =
```
Comment (mythrocks) [inline java/cuvs-java/src/main/java22/com/nvidia/cuvs/internal/TieredIndexImpl.java]: Unless I've missed something, this looks like a leak of the index-parameters.  The point of using a `CloseableHandle` to the index-parameters is that it be closed at the end of the usage-scope.  

This should look something like:
```java
try (var resourceAccess = resources.access();
     var indexParamsHandle = tieredIndexParameters != null
              ? segmentFromIndexParams(localArena, tieredIndexParameters)
              : CloseableHandle.NULL) {
  MemorySegment indexParamsMemorySegment = indexParamsHandle.handle();
  // Get host data
  MemorySegment hostDataSeg = ((CuVSHostMatrixImpl) dataset).memorySegment();
  // ...
}
```
As it stands, the index-params aren't cleaned up.

Comment (punAhuja) [reply java/cuvs-java/src/main/java22/com/nvidia/cuvs/internal/TieredIndexImpl.java]: Thanks for pointing this out @mythrocks Have fixed this by moving the handle declaration into the try-with-resources to fix this leak.

**Review by mythrocks — APPROVED** [review]
Thanks for making the changes, @punAhuja.  LGTM.
